services:
    todo_service_db:
        image: postgres:14-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: todo_service
        ports:
            - 5432:5432
